
version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable-git

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --update --no-cache docker-compose
      - run:
          name: Build and test
          command: |
            docker-compose build
            docker-compose up -d
            docker-compose exec api pytest
      - run:
          name: Stop services
          command: docker-compose down
workflows:
  version: 2.0
  build-and-test:
    jobs:
      - build