version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push API image
          command: |
            docker build -t anhhoang2910/frontend:latest ./client
            docker login -u $anhhoang2910 -p $0965120724Anh
            docker push anhhoang2910/frontend:latest
workflows:
  build-and-publish:
    jobs:
      - build:
          filters:
            branches:
              only: main
