version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push API image
          command: |
            docker compose up --build 
            
      
workflows:
  build-and-publish:
    jobs:
      - build:
          filters:
            branches:
              only: main
