version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push API image
          command: |
            docker build -t anhhoang2910/api:latest ./server/video-editing-api
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push anhhoang2910/api:latest
      - run:
          name: Build and push frontend image
          command: |
            docker build -t anhhoang2910/frontend:latest ./client
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push anhhoang2910/frontend:latest
workflows:
  build-and-publish:
    jobs:
      - build:
          filters:
            branches:
              only: main
